### ISSUE TITLE
The specific setting (e.g., batch-size) to reproduce the inference speed in Tab.3?

### ISSUE THREAD

**Issue by Openning07** [facebookresearch/LeViT#14]
In the Tab.3 of the paper, there are some values indicating the inference speed of LeViT models, such as 12880 img/s for LeViT-128S and 9266 img/s for LeViT-128.

Would you please list the specific setting (e.g., the batch-size, the type of GPU), because the same architecture can run with various inference speed under different settings.

**Comment by btgraham** [comment]
https://github.com/facebookresearch/LeViT/blob/main/speed_test.py
was run on a Tesla V100-SXM2-16GB, see
https://github.com/facebookresearch/LeViT/blob/main/.github/timings.txt
for details. GPU batch sizes are the highest power of 2 that fits in memory.

For comparison to other models, I would recommend re-running the benchmark for all models on the same machine, with as few other process running as possible.

**Comment by Openning07** [comment]
Thanks~
