### ISSUE TITLE
How to reproduce the CPU/Arm inference speed in Table 3?

### ISSUE THREAD

**Issue by panda1949** [facebookresearch/LeViT#15]
I have test DeiT/EfficientNet/LeViT on my iphone. Their speeds are comparable if they have similar FLOPs. But in Table 3, EfficientNet is much much slower than DeiT/LeViT. So I want to know how to reproduce the CPU/Arm inference speed in Table 3?

**Comment by btgraham** [comment]
The Arm timings are done on an Amazon server instance,
```
https://github.com/facebookresearch/LeViT/blob/main/.github/timings.txt
```
The speed was relatively slow compared to the baseline models, so we only show Intel and GPU timings in the main figure.
