### ISSUE TITLE
About the shape of attention_biases

### ISSUE THREAD

**Issue by ZhangLei999** [facebookresearch/LeViT#17]
Thanks for your work! 

When I run the code, I meet an error:
too many indices for tensor of dimension2.

Error file is "mypath/levit.py", the error code is "self.attention_biases[:, self.attention_bias_idxs] "

attention_biases shape: [4, 196]
attention_bias_idxs shape: [196, 196]
Is there something wrong with this code?

**Comment by btgraham** [comment]
It runs on my computer.
What version of torch are you running? (i.e `print(torch.__version__)`)
What do you get when you run `python speed_test.py`

**Comment by ZhangLei999** [comment]
Thanks for your reply.
The version of my torch is 1.7.1.
The type of self.attention_bias_idxs I changed to torch.bool.
