### ISSUE TITLE
Using LeViT model and pretrained weights for object detection on larger resolution 

### ISSUE THREAD

**Issue by QingXIA233** [facebookresearch/LeViT#25]
Hello,

Impressive work! I notice that the LeViT models are trained with images of 224x224. Recently, I have tried to use LeViT256(with your pretrained model weights) as backbone of my own object detection model. The input resolution of my model is 448x800, which means after patch embedding, the resolution becomes 28x50. In your model, the resolution after patch embedding is 14x14. Therefore, when I try to load the pretrained wights, the shape of attention_bias_idx doesn't match (weights: 14x14,14x14, model: 28x50, 28x50). For this problem, I came up with two possible compromise ways: 1. load the model weights without attention_bias_idx. I trained my OD model on Nuscenes and the results are not good. 2. load the model weights and perform nearest interpolation for attention_bias_idx, but logically this process doesn't make much sense to me. 

I wonder whether anyone has tried to use LeViT model and pretrained weights for larger resolution than 224x224. How should I solve the above mentioned problem? Or the weights of attention_bias_idx doesn't matter too much for the model performance on other datasets. Hope someone could provide some hints for me. Thanks!

**Comment by btgraham** [comment]
Thanks for your interest. LeViT models were designed to be efficient at resolution 224x224. Doubling the resolution means there are 4 times as many pixels, and quadratic attention uses 16x as much compute -- this is unlikely to be efficient. 

Instead you would want to either increase the downsampling in the convolutional feature extractor, or use attention within sliding windows, at a guess.
