### ISSUE TITLE
Question about training from Checkpoint.pth

### ISSUE THREAD

**Issue by mingqiJ** [facebookresearch/LeViT#27]
Hi,

I use this command to train
`python3 -m torch.distributed.launch --nproc_per_node=4 --use_env main.py --epochs 500 --model LeViT_256 --data-path /scratch/pytorch-image-models-master/imagenet --output_dir /scratch/LeViT-main/output`
My workstation is broken when it finish 70 epochs train for LeViT-256. So I want to re-start from 70 epochs. But when I use the same command, it start from 0 epoch. Does anyone know how to re-start from 70 epochs. The checkpoint file is in the output/ dictionary.

Thanks

**Comment by btgraham** [comment]
Use the --resume argument to identify the checkpoint to use, please.
