### ISSUE TITLE
Question about running the speed_test.py

### ISSUE THREAD

**Issue by irsLu** [facebookresearch/LeViT#30]
Hi~
I want to  run the speed_test.py, but there is an error as follow:
` q, k, v = qkv.view(B, N, self.num_heads, `
 `shape '[2048, 50176, 4, -1]' is invalid for input of size 308281344`
when I check the code, I find that the code remove batchnorm of model, and the patch_embed of model is also removed. Therefore, the transformer blocks can not reshape the input.
<img width="718" alt="image" src="https://user-images.githubusercontent.com/42465965/200749518-68c771f7-d98c-4d4c-abdd-c08fc879eb78.png">

<img width="210" alt="image" src="https://user-images.githubusercontent.com/42465965/200749538-facc6eed-12c1-49ff-80b9-912203231b01.png">

My question is how I fix this problem? 
And When I delete this line of removing batchnorm, I find the result of 'levit.LeViT_128S, 2048, 224'  is 20761 images/s on RTX 3090 which is a lot higher than what you reported  (12880 images/s reported in Tab 3). Is this result reasonable?
 I am looking forward to your reply, thx~.

**Comment by btgraham** [comment]
Hello. What is your `torch.__version__` please?

**Comment by irsLu** [comment]
> Hello. What is your `torch.__version__` please?

I'm so sorry~, I find it is my fault. I'm sorry to bother you. And good luck with your research

**Comment by btgraham** [comment]
No problem. Thanks for your interest.
