### ISSUE TITLE
problem of inference precision

### ISSUE THREAD

**Issue by aso538** [facebookresearch/LeViT#31]
Thank you very much for your open source. But when I reproduce the inference precision, when I use the model provided by the official, the inference precision is inconsistent with that given in readme. What is the reason.
--------------------------------------------------------------------------------------------------------------
i use the LeViT-256 Acc@1 81.584 Acc@5 95.464 loss 0.745

**Comment by btgraham** [comment]
The accuracy of any machine learning model will vary slightly between CPU and GPU, and between different versions of PyTorch, CUDNN, etc, due to numerical rounding errors. Unless the change in performance is large, this is to be expected.
