### ISSUE TITLE
Does it mean to use fuse when evaluating?

### ISSUE THREAD

**Issue by Yulv-git** [facebookresearch/LeViT#4]
https://github.com/facebookresearch/LeViT/blob/809adedaaeeb621fa3793f9197979102696a0955/main.py#L261

https://github.com/facebookresearch/LeViT/blob/809adedaaeeb621fa3793f9197979102696a0955/levit.py#L499

Excuse me, does the above line of code mean that fuse should be used when evaluating? Thank you!

**Comment by btgraham** [comment]
Conv2d(bias=False)+BatchNorm2d(affine=True) are replaced with a single BatchNorm2d(bias=True) module.
