### ISSUE TITLE
Can Levit work with non-square input?

### ISSUE THREAD

**Issue by aashusri** [facebookresearch/LeViT#6]
It throws an error when fed an input other than 224x224? Would it be possible to use it as a feature extractor for the non-squared input(either levit or levit_c)? 
example code.
` model = levit_c.LeViT_c_128S(num_classes=1000).to(device="cuda:0").eval()`
`features = model.blocks(model.patch_embed(torch.randn(4, 3, 256, 224, device='cuda:0'))) # throws an error for any resolution other than (224x224)`

**Comment by btgraham** [comment]
This is not currently supported, sorry.
Some research would be needed as to how to scale attention biases to different resolutions. 
Also, for larger images, full attention could become prohibitively expensive.
