### ISSUE TITLE
ResNet50+DeiT

### ISSUE THREAD

**Issue by Faith-Code** [facebookresearch/LeViT#8]
How to change the activation maps produced by cropped ResNet to adapt to DieT.  Can you release the code and pretrained model about this，Thanks a lot.

**Comment by btgraham** [comment]
You can switch from BCHW format to BNC format with the command
```
x = x.flatten(2).transpose(1, 2)
```
I am afraid we are only releasing the source code for the LeViT models, not the hybrid ResNet-50/DeiT models.
