### ISSUE TITLE
attention bias problem

### ISSUE THREAD

**Issue by DeidaraYang** [facebookresearch/LeViT#9]
Thanks for sharing! Well, I'm confused about the part of attention bias and I list a small example blow.

points = list(itertools.product(range(3), range(3)))
N = len(points)
attention_offsets = {}
idxs = []
for p1 in points:
    for p2 in points:
        offset = (abs(p1[0] - p2[0]), abs(p1[1] - p2[1]))
        if offset not in attention_offsets:
            attention_offsets[offset] = len(attention_offsets)
        idxs.append(attention_offsets[offset])
attention_biases = torch.nn.Parameter(
    torch.zeros(1, len(attention_offsets)))
attention_bias_idxs = torch.LongTensor(idxs).view(N, N)
print(attention_biases[:,attention_bias_idxs])

However, after I run this code, the result is all zero for attention_biases !? I think the reasonable answer is the content of attention_bias_idxs in each head.

**Comment by btgraham** [comment]
The bias is initialized to zero, but learnt as the network is trained, i.e.
```
torch.load('LeViT-128S-96703c44.pth')['model']['blocks.0.m.attention_biases'].std().item()
--> 5.0527262687683105
```
The attention_bias_idxs mean that the bias for pairs with the same offset is the same, i.e.
pairs [(1,2),(3,4)] and [(11,2),(13,4)]. both have offset (2,2).
